# Base settings
set -g prefix C-a
bind C-a send-prefix
unbind C-b
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",st-256color:Tc,xterm-256color:Tc,xterm-kitty:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename off
set -g renumber-windows on
set -sg escape-time 0
set -g mouse on

# Bindings
bind R source-file ~/.tmux.conf
bind f run -b ftwind

bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind C-p run-shell "tmux set-buffer \"$(xclip -selection clipboard -o)\"; tmux paste-buffer"
bind C-y run "tmux save-buffer ~/.tmux_buffer; xclip -selection clipboard ~/.tmux_buffer"
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"

bind C-k send-keys -R \; clear-history

bind -r C-2 select-layout even-horizontal
bind -r C-3 select-layout even-vertical

# Stop window switching from being repeatable
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# switch between sessions
bind -r ( switch-client -p
bind -r ) switch-client -n

# Prefixless bindings
bind -n C-Right next-window
bind -n C-Left previous-window

set -g status-style "bg=#cad0de fg=#e8e9ec bold"
set -g window-status-current-style "fg=#e8e9ec bg=#668e3d"
set -g window-status-style "fg=#e8e9ec bg=#757ca3"
set -g pane-active-border-style "fg=#668e3d bg=#e8e9ec"
set -g pane-border-style "fg=#33374c bg=#e8e9ec"
source-file ~/.tmux/jellybeans.tmux.conf
