if has("gui_macvim")
  " Fullscreen takes up entire screen
  set fuoptions=maxhorz,maxvert

  " set guifont=Sauce\ Code\ Powerline:h13
  set guifont=Sauce\ Code\ Powerline\ Light:h12

  set antialias
  " set background=dark
  colorscheme landscape
  set linespace=1
  syntax on

" Start without the toolbar
  set guioptions-=T
  set guioptions-=L
  set guioptions-=r
  set guioptions-=e

  augroup BgHighlight
    autocmd!
    autocmd WinEnter * set cul
    autocmd WinLeave * set nocul
  augroup END


  " tab navigation like firefox
  " nnoremap <C-t>     :tabnew<CR>
  " inoremap <C-t>     <Esc>:tabnew<CR>
  " nnoremap <C-S-tab> :tabprevious<CR>
  " nnoremap <C-tab>   :tabnext<CR>
  " inoremap <C-S-tab> <Esc>:tabprevious<CR>i
  " inoremap <C-tab>   <Esc>:tabnext<CR>i

  " Command-Return for fullscreen
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>

  " Map Command-# to switch tabs
  map  <D-0> 0gt
  imap <D-0> <Esc>0gt
  map  <D-1> 1gt
  imap <D-1> <Esc>1gt
  map  <D-2> 2gt
  imap <D-2> <Esc>2gt
  map  <D-3> 3gt
  imap <D-3> <Esc>3gt
  map  <D-4> 4gt
  imap <D-4> <Esc>4gt
  map  <D-5> 5gt
  imap <D-5> <Esc>5gt
  map  <D-6> 6gt
  imap <D-6> <Esc>6gt
  map  <D-7> 7gt
  imap <D-7> <Esc>7gt
  map  <D-8> 8gt
  imap <D-8> <Esc>8gt
  map  <D-9> 9gt
  imap <D-9> <Esc>9gt
endif
" Don't beep
set visualbell
