local config = require("user.config")
local utils = require("user.utils")
local themer = require("user.themer")

local colorscheme = "base46"

local M = {
	"AvengeMedia/base46",
	lazy = themer.lazy_load(colorscheme),
	priority = themer.priority_for(colorscheme),
	keys = themer.keys(colorscheme),
}

M.supported_variants = {
	"aquarium",
	"ashes",
	"aylin",
	"ayu_dark",
	"ayu_light",
	"ayu_mirage",
	"bearded-arc",
	"blossom_light",
	"carbonfox",
	"catppuccin-latte",
	"catppuccin",
	"chadracula-evondev",
	"chadracula",
	"chadtain",
	"chocolate",
	"darcula-dark",
	"dark_horizon",
	"decay",
	"default-dark",
	"default-light",
	"doomchad",
	"eldritch",
	"embark",
	"everblush",
	"everforest",
	"everforest_light",
	"falcon",
	"flex-light",
	"flexoki-light",
	"flexoki",
	"flouromachine",
	"gatekeeper",
	"github_dark",
	"github_light",
	"gorgoroth",
	"gruvbox",
	"gruvbox_light",
	"gruvchad",
	"hiberbee",
	"horizon",
	"jabuti",
	"jellybeans",
	"kanagawa-dragon",
	"kanagawa",
	"material-darker",
	"material-deep-ocean",
	"material-lighter",
	"melange",
	"midnight_breeze",
	"mito-laser",
	"monekai",
	"monochrome",
	"mountain",
	"nano-light",
	"neofusion",
	"nightfox",
	"nightlamp",
	"nightowl",
	"nord",
	"obsidian-ember",
	"oceanic-light",
	"oceanic-next",
	"one_light",
	"onedark",
	"onenord",
	"onenord_light",
	"oxocarbon",
	"palenight",
	"pastelDark",
	"pastelbeans",
	"penumbra_dark",
	"penumbra_light",
	"poimandres",
	"radium",
	"rosepine-dawn",
	"rosepine-moon",
	"rosepine",
	"rxyhn",
	"scaryforest",
	"seoul256_dark",
	"seoul256_light",
	"solarized_dark",
	"solarized_light",
	"solarized_osaka",
	"starlight",
	"sunrise_breeze",
	"sweetpastel",
	"tokyodark",
	"tokyonight",
	"tomorrow_night",
	"tundra",
	"vesper",
	"vscode_dark",
	"vscode_light",
	"wombat",
	"yoru",
	"zenburn",
}

M.default_variant = "default-dark"

M.config = function()
	if config.colorscheme ~= "base46" then
		return false
	end

	vim.cmd.colorscheme("base46-" .. themer.variant(M))
end

return M
