return {
	require("user.plugins.colorschemes.arctic"),
	require("user.plugins.colorschemes.ares"),
	require("user.plugins.colorschemes.catppuccin"),
	require("user.plugins.colorschemes.darkbox"),
	require("user.plugins.colorschemes.everforest"),
	require("user.plugins.colorschemes.ef-themes"),
	require("user.plugins.colorschemes.flexoki"),
	require("user.plugins.colorschemes.gruvbox"),
	-- remember: only enable one of the next two by using enabled = false for the other
	require("user.plugins.colorschemes.jellybeans-metalelf0"),
	require("user.plugins.colorschemes.jellybeans"),
	require("user.plugins.colorschemes.kanagawa"),
	require("user.plugins.colorschemes.kanso"),
	require("user.plugins.colorschemes.modus"),
	require("user.plugins.colorschemes.nightfox"),
	require("user.plugins.colorschemes.no-clown-fiesta"),
	require("user.plugins.colorschemes.oldworld"),
	require("user.plugins.colorschemes.oh-lucy"),
	require("user.plugins.colorschemes.one"),
	require("user.plugins.colorschemes.posterpole"),
	require("user.plugins.colorschemes.quietlight"),
	require("user.plugins.colorschemes.rose-pine"),
	require("user.plugins.colorschemes.shadow"),
	require("user.plugins.colorschemes.tokyonight"),
	require("user.plugins.colorschemes.yorumi"),
	require("user.plugins.colorschemes.vague"),
	require("user.plugins.colorschemes.ayu"),
	require("user.plugins.colorschemes.standard"),
	-- require("user.plugins.colorschemes.bamboo"),
	-- require("user.plugins.colorschemes.base16"),
	-- require("user.plugins.colorschemes.black-metal"),
	-- require("user.plugins.colorschemes.blue-moon"),
	-- require("user.plugins.colorschemes.boo"),
	-- require("user.plugins.colorschemes.citruszest"),
	-- require("user.plugins.colorschemes.edge"),
	-- require("user.plugins.colorschemes.freyeday"),
	require("user.plugins.colorschemes.github-nvim-theme"),
	require("user.plugins.colorschemes.gruvbox-material"),
	-- require("user.plugins.colorschemes.helix"),
	-- require("user.plugins.colorschemes.iceberg"),
	-- require("user.plugins.colorschemes.material"),
	-- require("user.plugins.colorschemes.mellifluous"),
	-- require("user.plugins.colorschemes.mellow"),
	-- require("user.plugins.colorschemes.miasma"),
	-- require("user.plugins.colorschemes.midnight"),
	-- require("user.plugins.colorschemes.monokai-pro"),
	require("user.plugins.colorschemes.moonfly"),
	-- require("user.plugins.colorschemes.moonwalk"),
	-- require("user.plugins.colorschemes.nano-theme"),
	require("user.plugins.colorschemes.neomodern"),
	-- require("user.plugins.colorschemes.night-owl"),
	-- require("user.plugins.colorschemes.nordic"),
	-- require("user.plugins.colorschemes.oak"),
	-- require("user.plugins.colorschemes.onedark"),
	-- require("user.plugins.colorschemes.oxocarbon"),
	-- require("user.plugins.colorschemes.papilio-dehaanii"),
	-- require("user.plugins.colorschemes.rasmus"),
	-- require("user.plugins.colorschemes.seoul256"),
	-- require("user.plugins.colorschemes.serenity"),
	-- require("user.plugins.colorschemes.vesper"),
	-- require("user.plugins.colorschemes.vscode_modern"),
	require("user.plugins.colorschemes.zenbones"),
	require("user.plugins.colorschemes.black-metal"),
	require("user.plugins.colorschemes.eldritch"),
}
