local config = require("user.config")
local utils = require("user.utils")
local themer = require("user.themer")

local colorscheme = "protesilaos"

local M = {
	"szymonwilczek/arete.nvim",
	lazy = themer.lazy_load(colorscheme),
	priority = themer.priority_for(colorscheme),
	keys = themer.keys(colorscheme),
}

M.supported_variants = {
	"doric-almond",
	"doric-beach",
	"doric-cherry",
	"doric-copper",
	"doric-coral",
	"doric-dark",
	"doric-earth",
	"doric-fire",
	"doric-jade",
	"doric-light",
	"doric-magma",
	"doric-marble",
	"doric-mermaid",
	"doric-oak",
	"doric-obsidian",
	"doric-pine",
	"doric-plum",
	"doric-siren",
	"doric-valley",
	"doric-walnut",
	"doric-water",
	"doric-wind",
	"ef-arbutus",
	"ef-arcadia",
	"ef-atlantis",
	"ef-autumn",
	"ef-bio",
	"ef-cherie",
	"ef-cyprus",
	"ef-dark",
	"ef-day",
	"ef-deuteranopia-dark",
	"ef-deuteranopia-light",
	"ef-dream",
	"ef-duo-dark",
	"ef-duo-light",
	"ef-eagle",
	"ef-elea-dark",
	"ef-elea-light",
	"ef-false",
	"ef-fig",
	"ef-frost",
	"ef-kassio",
	"ef-light",
	"ef-maris-dark",
	"ef-maris-light",
	"ef-melissa-dark",
	"ef-melissa-light",
	"ef-night",
	"ef-orange",
	"ef-owl",
	"ef-reverie",
	"ef-rosa",
	"ef-spring",
	"ef-summer",
	"ef-symbiosis",
	"ef-theme",
	"ef-tint",
	"ef-trio-dark",
	"ef-trio-light",
	"ef-tritanopia-dark",
	"ef-tritanopia-light",
	"ef-winter",
	"modus-operandi-deuteranopia",
	"modus-operandi-tinted",
	"modus-operandi-tritanopia",
	"modus-operandi",
	"modus-vivendi-deuteranopia",
	"modus-vivendi-tinted",
	"modus-vivendi-tritanopia",
	"modus-vivendi",
	"prot16-alto-dark",
	"prot16-alto-light",
	"prot16-archaic-dark",
	"prot16-archaic-light",
	"prot16-bionis-dark",
	"prot16-bionis-light",
	"prot16-blau-dark",
	"prot16-blau-light",
	"prot16-camo-dark",
	"prot16-camo-light",
	"prot16-caprice-dark",
	"prot16-caprice-light",
	"prot16-cyprium-dark",
	"prot16-cyprium-light",
	"prot16-equinox-dark",
	"prot16-equinox-light",
	"prot16-ficus-dark",
	"prot16-ficus-light",
	"prot16-flowerbed-dark",
	"prot16-flowerbed-light",
	"prot16-fortuna-dark",
	"prot16-fortuna-light",
	"prot16-gaia-dark",
	"prot16-gaia-light",
	"prot16-hinterland-dark",
	"prot16-hinterland-light",
	"prot16-hyperion-dark",
	"prot16-hyperion-light",
	"prot16-magus-dark",
	"prot16-magus-light",
	"prot16-nefelio-dark",
	"prot16-nefelio-light",
	"prot16-neptune-dark",
	"prot16-neptune-light",
	"prot16-noir-dark",
	"prot16-noir-light",
	"prot16-ocarina-dark",
	"prot16-ocarina-light",
	"prot16-oliveira-dark",
	"prot16-oliveira-light",
	"prot16-orionis-dark",
	"prot16-orionis-light",
	"prot16-overgrowth-dark",
	"prot16-overgrowth-light",
	"prot16-playa-dark",
	"prot16-playa-light",
	"prot16-seabed-dark",
	"prot16-seabed-light",
	"prot16-sonho-dark",
	"prot16-sonho-light",
	"prot16-symbiosis-dark",
	"prot16-symbiosis-light",
	"prot16-termina-dark",
	"prot16-termina-light",
	"prot16-vin-dark",
	"prot16-vin-light",
	"standard-adwaita",
	"standard-dark-tinted",
	"standard-dark",
	"standard-light-tinted",
	"standard-light",
	"standard-wombat",
	"tempus_autumn",
	"tempus_classic",
	"tempus_dawn",
	"tempus_day",
	"tempus_dusk",
	"tempus_fugit",
	"tempus_future",
	"tempus_night",
	"tempus_past",
	"tempus_rift",
	"tempus_spring",
	"tempus_summer",
	"tempus_tempest",
	"tempus_totus",
	"tempus_warp",
	"tempus_winter",
}

M.default_variant = "modus-vivendi"

M.config = function()
	require("arete").setup({
		transparent = config.transparent,
		on_highlights = function(hls, name)
			local overrides = {}
			-- if config.transparent then
			overrides.ColorColumn = { bg = "NONE" }
			overrides.LineNr = { bg = "NONE" }
			-- end
			return overrides
		end,
	})
	vim.cmd("colorscheme " .. themer.variant(M))
end

return M
