require("user.options")
require("user.keymaps")
require("user.lazy")
require("user.utils")
require("user.colorscheme")
require("user.colorscheme_utils")
require("user.neovide")
require("user.autocommands")
require("user.digraphs")
require("user.fvim")

require("ui").load_ui_plugins()
