require("user.options")
require("user.keymaps")
require("user.lazy")
require("user.utils")
require("user.colorscheme")
require("user.telescope")
require("user.treesitter")
require("user.comment")
require("user.project")
require("user.neovide")
require("user.autocommands")
-- require "user.neorg"
require("user.neotest")
require("user.digraphs")
require("user.gh-nvim")
require("user.fvim")
