require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.impatient"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.indentline"
require "user.alpha"
require "user.legendary"
-- remember: whichkey must come AFTER legendary!
require "user.whichkey"
require "user.autocommands"
require "user.fzf-notational-velocity"
require "user.surround"
-- require "user.hop"
-- require "user.lightspeed"
require 'user.leap'
require "user.todo-comments"
require "user.neorg"
require "user.orgmode"
-- require 'user.aerial'
require "user.test-nvim"
require 'user.digraphs'
